### ISSUE TITLE
Reports: Export to CSV: missing first row

### ISSUE THREAD

**Issue by dakur** [grifart/mautic#2]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

When you choose Export to CSV feature in Reports, first row is missing in the exported file.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.20 |
### Steps to reproduce:
1. Create new report.
2. Go to created report and select Export to CSV.
##

**Comment by jkuchar** [comment]
@dakur this issue should be reported into original repo, not in the fork. ;-)

**Comment by dakur** [comment]
@jkuchar To byl účel. A můžeš na mě mluvit česky. :-) V originálním repu to je taky, tady jsme to dali, abychom věděli, co chceme měnit přednostně sami.

**Comment by jkuchar** [comment]
Odpovídal jsem na anglicky psaný bug report. ;)
