### ISSUE TITLE
Reports: Export to Excel: does not work

### ISSUE THREAD

**Issue by dakur** [grifart/mautic#3]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

When you choose Export to Excel feature in Reports, nothing happens.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.20 |
### Steps to reproduce:
1. Create new report.
2. Go to created report and select Export to Excel.
### Log errors:

None found.

**Comment by jkuchar** [comment]
@dakur you have reported this to our fork... It should go into original repo.
